name: Build images
run-name: Build images
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '30 5 */5 * *'

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: install actions deps
        run: | 
          dnf install -y nodejs git
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build selected images
        run: | 
          podman build ./system-toolbox --tag system-toolbox:latest
          podman build ./cloud-toolbox --tag cloud-toolbox:latest
      - name: login to registry
        run: podman login -u "${{ secrets.PACKAGES_USERNAME }}" -p "${{ secrets.PACKAGES_PASSWD }}" gitea.maciej.cloud
      - name: Push image
        run: |
          # tagging
          podman tag system-toolbox:latest gitea.maciej.cloud/packages/system-toolbox:latest 
          podman tag cloud-toolbox:latest gitea.maciej.cloud/packages/cloud-toolbox:latest 
          # pushing
          podman push gitea.maciej.cloud/packages/system-toolbox:latest
          podman push gitea.maciej.cloud/packages/cloud-toolbox:latest
